In [1]:
print("Hi")

Hi


In [2]:
import numpy as np
ar=np.array([1,2,3,4])
print(type(ar))

<class 'numpy.ndarray'>


In [3]:
a=np.arange(6)
type(a)

numpy.ndarray

In [4]:
print(a)

[0 1 2 3 4 5]


In [5]:
b=np.arange(12).reshape(4,3)

In [6]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
print(b[0],0)

[0 1 2] 0


In [8]:
c=np.arange(16).reshape(2,2,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [9]:
print(c[1])

[[ 8  9 10 11]
 [12 13 14 15]]


In [10]:
s=np.arange(1000)
print(s)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [11]:
s=np.arange(10000)
print(s)

[   0    1    2 ... 9997 9998 9999]


In [12]:
np.set_printoption(threshold=np.nan)
print(np.arange(10000).reshape(100,100))

AttributeError: module 'numpy' has no attribute 'set_printoption'

In [13]:
print(np.arange(10000).reshape(100,100))
np.set_printoption(threshold=np.nan)
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


AttributeError: module 'numpy' has no attribute 'set_printoption'

In [14]:
arr1=np.array(object=[1,2,3], dtype='int')#1D
arr2=np.array([[1.5,2,3],[4,5,6],[7,8,9.5]], dtype='float')#2D
arr3=np.array([[(1.5,2,3),(4,5,6)], [(3,2,1),(5,5,8)]], dtype='int')#3D

In [16]:
print("1-D-->\n{}\n2-D-->\n{}\n 3-D-->\n{}".format(arr1,arr2,arr3))

1-D-->
[1 2 3]
2-D-->
[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9.5]]
 3-D-->
[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [5 5 8]]]


In [18]:
print(type(arr1),type(arr2),type(arr3))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [19]:
print(arr1.shape,arr2.shape,arr3.shape)

(3,) (3, 3) (2, 2, 3)


In [20]:
print(arr1.size,arr2.size,arr3.size)

3 9 12


In [21]:
print(arr1.dtype,arr2.dtype,arr3.dtype)

int32 float64 int32


In [22]:
arr1=arr1.astype('float')
print(arr1.dtype,arr2.dtype,arr3.dtype)
print(arr1)

float64 float64 int32
[1. 2. 3.]


In [23]:
print(arr2)

[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9.5]]


In [24]:
print(np.delete(arr=arr2,obj=[0,2,4]))#Obj is index of element one wants to delete;

[2.  4.  6.  7.  8.  9.5]


In [25]:
print(arr2)

[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9.5]]


In [26]:
np.delete(arr=arr2,obj[1,2],axis=1)

SyntaxError: positional argument follows keyword argument (<ipython-input-26-33ac4139fc40>, line 1)

In [27]:
np.delete(arr=arr2, obj[1,2] ,axis=1)

SyntaxError: positional argument follows keyword argument (<ipython-input-27-34fa8c34888a>, line 1)

In [28]:
np.delete(arr=arr2,obj=[1,2],axis=1)

array([[1.5],
       [4. ],
       [7. ]])

In [29]:
np.delete(arr=arr2,obj=1,axis=0)

array([[1.5, 2. , 3. ],
       [7. , 8. , 9.5]])

In [30]:
#Slicing

import numpy as np
a=np.arange(11)**2
print(a)

[  0   1   4   9  16  25  36  49  64  81 100]


In [31]:
print(type(a))

<class 'numpy.ndarray'>


In [32]:
print(a[2:7])#execludes last value

[ 4  9 16 25 36]


In [33]:
print(a[2:-2])

[ 4  9 16 25 36 49 64]


In [34]:
a[2:]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [35]:
a[2:-2]

array([ 4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [36]:
a[:7]

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

In [37]:
a[:11:2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)

In [38]:
a[: :2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)

In [39]:
a[: :-1]#reverse the string , from last to starting value

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [40]:
a[-1:-4]

array([], dtype=int32)

In [41]:
a[-1:-4]

array([], dtype=int32)

In [42]:
Students=np.array([['Rocky','Shaggy','Edge','Mark'],
                  [65,78,90,81],
                  [71,82,79,922]])

In [43]:
print(Students)

[['Rocky' 'Shaggy' 'Edge' 'Mark']
 ['65' '78' '90' '81']
 ['71' '82' '79' '922']]


In [44]:
print(Student.shape)

NameError: name 'Student' is not defined

In [45]:
print(Students.shape)

(3, 4)


In [46]:
Students[0]

array(['Rocky', 'Shaggy', 'Edge', 'Mark'], dtype='<U6')

In [47]:
Students[1]

array(['65', '78', '90', '81'], dtype='<U6')

In [48]:
Students[2]

array(['71', '82', '79', '922'], dtype='<U6')

In [49]:
Students[0,1]#0 row and 1st index it wil display

'Shaggy'

In [50]:
Students[1,3]

'81'

In [51]:

a = np.array([[1,2], [3, 4], [5, 6]])

In [52]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [53]:
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"


[1 4 5]


In [54]:
Students[0:2,2:4]

array([['Edge', 'Mark'],
       ['90', '81']], dtype='<U6')

In [55]:
Students[:1,2]

array(['Edge'], dtype='<U6')

In [56]:
Students[:1:2]

array([['Rocky', 'Shaggy', 'Edge', 'Mark']], dtype='<U6')

In [57]:
Students[:,1:2]

array([['Shaggy'],
       ['78'],
       ['82']], dtype='<U6')

In [58]:
Students[:,1,3]

IndexError: too many indices for array

In [59]:
Students[:,1:3]

array([['Shaggy', 'Edge'],
       ['78', '90'],
       ['82', '79']], dtype='<U6')

In [60]:
Students[0:2:1]

array([['Rocky', 'Shaggy', 'Edge', 'Mark'],
       ['65', '78', '90', '81']], dtype='<U6')

In [61]:
Students[0:2,1:]#all rows and from 2nd index, ignore 3rd row

array([['Shaggy', 'Edge', 'Mark'],
       ['78', '90', '81']], dtype='<U6')

In [62]:
Students[:]

array([['Rocky', 'Shaggy', 'Edge', 'Mark'],
       ['65', '78', '90', '81'],
       ['71', '82', '79', '922']], dtype='<U6')

In [63]:
Students[:]#All elements

array([['Rocky', 'Shaggy', 'Edge', 'Mark'],
       ['65', '78', '90', '81'],
       ['71', '82', '79', '922']], dtype='<U6')

In [64]:
print(Students)

[['Rocky' 'Shaggy' 'Edge' 'Mark']
 ['65' '78' '90' '81']
 ['71' '82' '79' '922']]


In [65]:
Students[-1:]

array([['71', '82', '79', '922']], dtype='<U6')

In [66]:
Students[-1,:]#prints last row and al the columns

array(['71', '82', '79', '922'], dtype='<U6')

In [67]:
Students[-3:-1,-2:]#   (-3:-1) --> (1set) and  (-2 till last)

array([['Edge', 'Mark'],
       ['90', '81']], dtype='<U6')

In [68]:
Students[0,...] #all columns of first row

array(['Rocky', 'Shaggy', 'Edge', 'Mark'], dtype='<U6')

In [69]:
Students[...,1]#All rows and one column

array(['Shaggy', '78', '82'], dtype='<U6')

In [70]:
Students[...,1].shape

(3,)

In [71]:
Students[:,1:2]#all rows and 2nd column

array([['Shaggy'],
       ['78'],
       ['82']], dtype='<U6')

In [72]:
Students[:,1:2].shape

(3, 1)

In [73]:
#array indexing
randMat=np.random.rand(4,3)#random matrix with given shape
randMat

array([[0.92221841, 0.78076209, 0.17557495],
       [0.09481806, 0.67431706, 0.80141143],
       [0.05547234, 0.56887291, 0.71706283],
       [0.99985226, 0.31596928, 0.7168152 ]])

In [74]:
randMat[0,1] #0th row and 1st column

0.7807620886664751

In [75]:
print(randMat[0],randMat[0:1])

[0.92221841 0.78076209 0.17557495] [[0.92221841 0.78076209 0.17557495]]


In [76]:
print(randMat[0],randMat[0,:1])

[0.92221841 0.78076209 0.17557495] [0.92221841]


In [77]:
randMat[:,0]

array([0.92221841, 0.09481806, 0.05547234, 0.99985226])

In [78]:
randMat.shape

(4, 3)

In [79]:
randMat[1,:]=0#2nd row and all the columns r initialising to 0
randMat

array([[0.92221841, 0.78076209, 0.17557495],
       [0.        , 0.        , 0.        ],
       [0.05547234, 0.56887291, 0.71706283],
       [0.99985226, 0.31596928, 0.7168152 ]])

In [80]:
randMat[0:2]#there is no comma so only rows not colums

array([[0.92221841, 0.78076209, 0.17557495],
       [0.        , 0.        , 0.        ]])

In [82]:
randMat[[0,2,3]]#

array([[0.92221841, 0.78076209, 0.17557495],
       [0.05547234, 0.56887291, 0.71706283],
       [0.99985226, 0.31596928, 0.7168152 ]])

In [83]:
randMat[0:2,0:2]

array([[0.92221841, 0.78076209],
       [0.        , 0.        ]])

In [84]:
randMat[-1]#last row

array([0.99985226, 0.31596928, 0.7168152 ])

In [85]:
randMat[::1,::2]#all rows and skio 2nd index values

array([[0.92221841, 0.17557495],
       [0.        , 0.        ],
       [0.05547234, 0.71706283],
       [0.99985226, 0.7168152 ]])

In [86]:
randMat.shape

(4, 3)

In [87]:
a[-1:-4]

array([], shape=(0, 2), dtype=int32)